version: 2
project_name: fakegameserver
dist: dist

env:
  - CGO_ENABLED=0

builds:
  - id: gameserver
    binary: gameserver
    main: ./cmd/gameserver
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

changelog:
  disable: true

archives:
  - id: gameserver
    formats: ['binary']
    allow_different_binary_count: true

release:
  disable: true

snapshot:
  version_template: "dev-{{ slice .FullCommit 0 8}}"

dockerhub:
  - images:
    - antiphp/fakegameserver
    full_description:
      from_file:
        path: ./README.md

dockers:
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - gameserver
    image_templates:
      - "docker.io/antiphp/fakegameserver:{{ .Tag }}"
      - "docker.io/antiphp/fakegameserver:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
